# Generated by Django 4.2.6 on 2023-10-23 21:24

from django.db import migrations, models
import django.db.models.deletion
import schememanager.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "kvk_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("kvk_registration_start", models.DateField(blank=True, null=True)),
                ("kvk_registration_end", models.DateField(blank=True, null=True)),
                ("kvk_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "billing_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[("requestor", "Requestor"), ("issuer", "Issuer")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name_nl", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=schememanager.models.get_new_logo_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifier",
                        to="schememanager.organization",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        limit_choices_to={"scheme_type": "requestor"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schememanager.scheme",
                    ),
                ),
            ],
            options={
                "unique_together": {("scheme", "slug")},
            },
        ),
        migrations.CreateModel(
            name="VerifierSessionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condiscon", models.JSONField()),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(null=True)),
                ("context_description_en", models.TextField(null=True)),
                ("context_description_nl", models.TextField(null=True)),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_requests",
                        to="schememanager.verifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifierHostname",
            fields=[
                (
                    "hostname",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dns_challenge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dns_challenge_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dns_challenge_verified", models.BooleanField(default=False)),
                (
                    "dns_challenge_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostnames",
                        to="schememanager.verifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifierAttributeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_id", models.CharField(max_length=100)),
                ("reason_en", models.TextField()),
                ("reason_nl", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="schememanager.verifiersessionrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationAdmin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins",
                        to="schememanager.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "email")},
            },
        ),
    ]
