# Generated by Django 5.0.3 on 2024-03-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schememanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifier",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verifier_registrations",
                to="schememanager.organization",
            ),
        ),
    ]
