# Generated by Django 5.0.3 on 2024-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schememanager", "0002_alter_verifier_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifierhostname",
            name="manually_verified",
            field=models.BooleanField(default=False),
        ),
    ]
