name: Ruff Linter with PR Review Comments

on:
  pull_request:
    branches: [main]

jobs:
  ruff-reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - run: pip install ruff

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          tool_name: ruff
          level: warning
          fail_on_error: false
          filter_mode: diff_context
          command: ruff check --format=compact .
