services:
  demo-schemes:
    container_name: yivi-portal-demo-schemes
    image: ghcr.io/privacybydesign/irma:edge
    command: >
      scheme download /schemes https://schemes.staging.yivi.app/pbdf-staging
    volumes:
      - ./downloads/schemes:/schemes

  yivi:
    container_name: yivi-portal-yivi
    image: ghcr.io/privacybydesign/irma:edge
    command: >
      server -v --no-email --no-tls --url ${YIVI_SERVER_URL:-http://localhost:8080} --port 8080
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8080:8080
    volumes:
      - ./downloads/schemes:/schemes
    environment:
      YIVI_SERVER_TOKEN: ${YIVI_SERVER_TOKEN}
      IRMASERVER_SCHEMES_PATH: /schemes

  database:
    image: postgres:13.3-alpine
    container_name: yivi-portal-db
    restart: unless-stopped
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

  yivi-portal:
    container_name: yivi-portal
    build:
      context: .
    restart: unless-stopped
    command: /bin/sh /app/entrypoint_dev.sh
    networks:
      - web
      - db
    ports:
      - 8000:8000
    depends_on:
      - database
      - yivi
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      YIVI_SERVER_URL: ${YIVI_SERVER_URL:-http://yivi:8080}
      YIVI_SERVER_TOKEN: ${YIVI_SERVER_TOKEN}
      DJANGO_SETTINGS_MODULE: yivi_portal.settings.development
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost}
    healthcheck:
      test: ['CMD', 'python', 'manage.py', 'check']
      interval: 60s
      timeout: 20s
      retries: 3

  yivi-portal-cron:
    container_name: yivi-portal-cron
    build:
      context: .
    entrypoint: ['/bin/sh', '/app/entrypoint_cron.sh']
    restart: unless-stopped
    networks:
      - web
      - db
    depends_on:
      - database
      - yivi
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: yivi_portal.settings.development

networks:
  web:
  db:

volumes:
  postgres-data:
