FROM node:18-alpine AS frontend-builder

WORKDIR /app

COPY portal_frontend /app
RUN npm install && npm run build

# Stage 2: Serve frontend with Nginx
FROM nginx:alpine AS nginx

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy frontend build output to Nginx web root
COPY --from=frontend-builder /app/out /usr/share/nginx/html

# Expose HTTP port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]