# Generated by Django 5.0.13 on 2025-04-30 06:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
