# Generated by Django 5.0.13 on 2025-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0002_alter_organization_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                related_name="users", to="portal_backend.organization"
            ),
        ),
    ]
