# Generated by Django 5.0.13 on 2025-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0002_alter_organization_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "organization")},
        ),
    ]
