# Generated by Django 5.0.13 on 2025-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0004_remove_relyingparty_approved_rp_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relyingparty",
            name="reviewed_rejected",
        ),
    ]
