# Generated by Django 5.0.13 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0004_remove_relyingparty_approved_rp_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attestationprovider",
            name="approved_ap_details",
        ),
        migrations.RemoveField(
            model_name="attestationprovider",
            name="published_ap_details",
        ),
        migrations.AddField(
            model_name="attestationprovider",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
