# Generated by Django 5.0.13 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal_backend",
            "0006_remove_attestationprovider_approved_ap_details_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attestationprovider",
            name="published",
        ),
        migrations.AddField(
            model_name="attestationprovider",
            name="approved_ap_details",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="attestationprovider",
            name="published_ap_details",
            field=models.JSONField(null=True),
        ),
    ]
