# Generated by Django 5.0.13 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0007_remove_attestationprovider_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestationprovider",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
