# Generated by Django 5.0.13 on 2025-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal_backend",
            "0006_remove_attestationprovider_approved_ap_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="condiscon",
            name="context_description_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="condiscon",
            name="context_description_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
