# Generated by Django 5.0.13 on 2025-05-21 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0009_alter_condiscon_context_description_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credentialattribute",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AlterUniqueTogether(
            name="credentialattribute",
            unique_together={("credential", "name_en")},
        ),
        migrations.RemoveField(
            model_name="credential",
            name="credential_tag",
        ),
        migrations.AddField(
            model_name="credential",
            name="credential_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="deprecated_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="issue_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="shortname_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="shortname_nl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="should_be_singleton",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="credentialattribute",
            name="description_en",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credentialattribute",
            name="description_nl",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credentialattribute",
            name="name_nl",
            field=models.CharField(default="asda", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="credential",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="name_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
