# Generated by Django 5.0.13 on 2025-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0010_rename_name_credentialattribute_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attestationprovider",
            name="approved_ap_details",
            field=models.JSONField(null=True),
        ),
        migrations.RemoveField(
            model_name="attestationprovider",
            name="published_ap_details",
            field=models.JSONField(null=True),
        ),
    ]
