# Generated by Django 5.0.13 on 2025-05-21 11:23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0010_rename_name_credentialattribute_name_en_and_more"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="relyingparty",
            name="reviewed_rejected",
        ),
    ]
