# Generated by Django 5.0.13 on 2025-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0012_rename_base_url_attestationprovider_contact_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialattribute",
            name="credential_attribute_id",
            field=models.CharField(default="sdffds", max_length=100),
            preserve_default=False,
        ),
    ]
