# Generated by Django 5.0.13 on 2025-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0013_credentialattribute_credential_attribute_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestationprovider",
            name="ap_slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
