# Generated by Django 5.0.13 on 2025-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0015_rename_contact_yivitrustmodelenv_contact_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relyingparty",
            name="reviewed_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
