# Generated by Django 5.0.13 on 2025-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0015_rename_contact_yivitrustmodelenv_contact_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="yivitrustmodelenv",
            name="name_en",
            field=models.CharField(
                default="Privacy By Design Foundation", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yivitrustmodelenv",
            name="name_nl",
            field=models.CharField(default="stichting pbdf", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yivitrustmodelenv",
            name="scheme_id",
            field=models.CharField(default="pbdf", max_length=100),
            preserve_default=False,
        ),
    ]
