# Generated by Django 5.0.13 on 2025-06-04 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0016_alter_relyingparty_reviewed_accepted"),
        (
            "portal_backend",
            "0016_yivitrustmodelenv_name_en_yivitrustmodelenv_name_nl_and_more",
        ),
    ]

    operations = []
