# Generated by Django 5.0.13 on 2025-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0018_remove_organization_registration_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attestationprovider",
            constraint=models.UniqueConstraint(
                fields=("yivi_tme", "ap_slug"), name="unique_ap_slug_per_yivi_tme"
            ),
        ),
    ]
