# Generated by Django 5.0.13 on 2025-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0019_attestationprovider_unique_ap_slug_per_yivi_tme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationprovider",
            name="ap_slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
