# Generated by Django 5.0.13 on 2025-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0020_alter_attestationprovider_ap_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yivitrustmodelenv",
            name="keyshare_server",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
