# Generated by Django 5.0.13 on 2025-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0021_alter_yivitrustmodelenv_keyshare_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yivitrustmodelenv",
            name="keyshare_website",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
