# Generated by Django 5.0.13 on 2025-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0022_alter_yivitrustmodelenv_keyshare_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yivitrustmodelenv",
            name="keyshare_attribute",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
