# Generated by Django 5.0.13 on 2025-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0023_alter_yivitrustmodelenv_keyshare_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yivitrustmodelenv",
            name="minimum_android_version",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="yivitrustmodelenv",
            name="minimum_ios_version",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
