# Generated by Django 5.0.13 on 2025-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal_backend",
            "0024_alter_yivitrustmodelenv_minimum_android_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attestationprovider",
            name="deprecated_since",
            field=models.DateField(blank=True, null=True),
        ),
    ]
