# Generated by Django 5.0.13 on 2025-06-11 11:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0025_attestationprovider_deprecated_since"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="verified_at",
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
