# Generated by Django 5.0.13 on 2025-06-18 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0026_remove_organization_verified_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credentialattribute",
            old_name="credential_attribute_id",
            new_name="credential_attribute_tag",
        ),
    ]
