# Generated by Django 5.0.13 on 2025-06-27 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0028_alter_relyingpartyhostname_hostname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relyingpartyhostname",
            name="hostname",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_domain",
                        message="Enter a valid domain (e.g., example.com).",
                        regex="([a-z0-9A-Z]\\.)*[a-z0-9-]+\\.([a-z0-9]{2,24})+(\\.co\\.([a-z0-9]{2,24})|\\.([a-z0-9]{2,24}))*",
                    )
                ],
            ),
        ),
    ]
