# Generated by Django 5.0.13 on 2025-07-07 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0029_alter_relyingpartyhostname_hostname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="approved_logo",
        ),
        migrations.AlterField(
            model_name="relyingpartyhostname",
            name="hostname",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_domain",
                        message="Enter a valid domain (e.g., example.com).",
                        regex="^(?=^.{1,253}$)(([a-z\\d]([a-z\\d-]{0,62}[a-z\\d])*[\\.]){1,3}[a-z]{1,61})$",
                    )
                ],
            ),
        ),
    ]
