# Generated by Django 5.0.13 on 2025-08-11 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0029_alter_relyingpartyhostname_hostname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relyingpartyhostname",
            name="hostname",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_domain",
                        message="Enter a valid domain (e.g., example.com).",
                        regex="^((?:([a-z0-9]\\.|[a-z0-9][a-z0-9\\-]{0,61}[a-z0-9])\\.)+)([a-z0-9]{2,63}|(?:[a-z0-9][a-z0-9\\-]{0,61}[a-z0-9]))\\.?$",
                    )
                ],
            ),
        ),
    ]
