# Generated by Django 5.0.13 on 2025-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0030_remove_organization_approved_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialattribute",
            name="optional",
            field=models.BooleanField(default=False),
        ),
    ]
