# Generated by Django 5.0.13 on 2025-08-04 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0030_remove_organization_approved_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relyingpartyhostname",
            name="hostname",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_domain",
                        message="Enter a valid domain (e.g., example.com).",
                        regex=r"^(?!.{255})[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*\.(?!-)(?:[a-zA-Z0-9-]{2,63})(?<!-)\.?$",
                    )
                ],
            ),
        ),
    ]
