# Generated by Django 5.0.13 on 2025-10-17 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0031_credentialattribute_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrmaServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Irma Server",
                "verbose_name_plural": "Irma Servers",
            },
        ),
    ]
