# Generated by Django 5.0.13 on 2025-10-20 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal_backend", "0031_credentialattribute_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrmaServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("version", models.CharField(max_length=35)),
            ],
            options={
                "verbose_name": "Irma Server",
                "verbose_name_plural": "Irma Servers",
            },
        ),
        migrations.AddConstraint(
            model_name="irmaserver",
            constraint=models.UniqueConstraint(
                fields=("email", "version"), name="unique_email_version"
            ),
        ),
    ]
