# Build Stage
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production Stage
FROM nginx:stable-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --chmod=0755 entrypoint.sh /docker-entrypoint.d/
COPY --from=build /app/dist /app
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]