"""Curated demo issuance values for irma-demo credentials.

Single source of truth for the demo values that pre-fill the demo-issuance form
on the attribute index. Applied by the AP sync (trusted_aps_import) when it
creates/updates CredentialAttribute rows for the 'demo' environment.

Keyed by '<issuer>.<credential_id>' (== organization.slug + '.' + credential_id),
then by attribute id (== credential_attribute_tag).

Conventions (one consistent fictional Dutch persona, 'Jan de Vries'):
  - dates DD-MM-YYYY; issue dates 01-01-2024, expiry 01-01-2030; DOB 01-01-1990
  - booleans / age-limit attributes: 'yes' / 'no' (IRMA verifiers require yes/no)
  - image attributes (photo/logo/...): empty string (cannot type an image)
  - test BSN 999999990, IBAN NL91ABNA0417164300, email jan.devries@example.com
"""

DEMO_CREDENTIAL_VALUES: dict[str, dict[str, str]] = {
    "alliander.connection": {
        "eangas": "871234567890123456",
        "eanelec": "871234567890654321",
        "pseudonym": "pseudo-ABC123",
    },
    "amsterdam.openStadBallot": {
        "ballot": "yes",
    },
    "amsterdamVorin.taxiZoneExemption": {
        "exemptionNumber": "TZE-2024-0042",
        "validFrom": "01-01-2024",
        "validTo": "01-01-2030",
    },
    "asito.loonstaat": {
        "employer": "Demo B.V.",
        "payrollTaxDiscount": "yes",
        "disabledPersonDiscount": "no",
        "payrollTimeframe": "01-01-2024 tot 31-01-2024",
        "incomeContractNumber": "1",
        "payInMoney": "3000",
        "payNotInMoney": "0",
        "payFromFunds": "0",
        "rebatesBeforeTax": "0",
        "employeeInsuranceLawPay": "3000",
        "healthInsuranceLawPay": "3000",
        "socialInsurancePay": "3000",
        "socialInsurancePremium": "450",
        "withheldZvwPay": "165",
        "amountPaid": "2385",
        "deductedWorkInsurance": "120",
        "careerSavingsPlanDiscount": "0",
    },
    "asito.paysheet": {
        "grossSalary": "3000",
        "grossSalaryComponents": "Basisloon 2800, toeslag 200",
        "wnPremium": "150",
        "employeePremium": "120",
        "netSalaryAllocations": "2300",
        "netSalaryDeductions": "700",
        "vtEmployer": "240",
        "solidarityContribution": "30",
    },
    "belastingdienst.verzamelinkomen": {
        "year": "2023",
        "totalincome": "36000",
        "box1": "36000",
        "box2": "0",
        "box3": "0",
        "incomelevel": "Gemiddeld",
    },
    "belastingdienst.verzamelinkomenhuishouden": {
        "year": "2024",
        "totalincome": "36000",
        "belowsocialhousing": "yes",
        "belowexceptionsocialhousing": "yes",
    },
    "chipsoft.bsn": {
        "bsn": "999999990",
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "dateofbirth": "01-01-1990",
    },
    "chipsoft.hix": {
        "usertype": "Patient",
        "usercode": "USR123456",
        "issuenumber": "1",
    },
    "cis.complianceCheck": {
        "initials": "J.",
        "firstnames": "Jan",
        "familyname": "de Vries",
        "surname": "de Vries",
        "dateofbirth": "01-01-1990",
        "gender": "M",
        "sanctionCheck": "yes",
        "nationality": "Nederlandse",
        "digidlevel": "Substantieel",
    },
    "cis.digitalInsurancePassport": {
        "initials": "J.",
        "prefix": "de",
        "surname": "Vries",
        "gender": "M",
        "dateofbirth": "01-01-1990",
        "countryofbirth": "Nederland",
        "legalInsuranceChecks": "No hits",
        "assuranceLevel": "Hoog",
    },
    "cluis.energieConclusie": {
        "periode": "01-01-2024 tot 31-12-2024",
        "gas": "1100 m3",
        "stroom": "2800 kWh",
    },
    "cluis.inkomenConclusie": {
        "periode": "01-01-2024 - 31-12-2024",
        "inkomen": "3000",
        "bracket": "2500-3500",
        "bron": "UWV",
        "bronLogo": "",
        "beleidsbepaler": "Stichting Cluis",
    },
    "cluis.vermogenConclusie": {
        "periode": "01-01-2024 tot 31-12-2024",
        "vermogen": "15000",
        "bracket": "10000-20000",
        "bron": "De Hollandsche Bank",
        "bronLogo": "",
        "beleidsbepaler": "Jan de Vries",
    },
    "coronameting.login": {
        "pseudonym": "jan-de-vries-8f3a",
    },
    "demo-airline.boardingpass": {
        "firstname": "Jan",
        "lastname": "de Vries",
        "flight": "KL1234",
        "from": "AMS",
        "to": "LHR",
        "seat": "14C",
        "date": "01-07-2026",
        "time": "10:45",
        "gate": "D7",
    },
    "DemoDuo.demodiploma": {
        "firstname": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "dateofbirth": "01-01-1990",
        "gender": "M",
        "education": "Informatica",
        "degree": "Bachelor",
        "profile": "Natuur en Techniek",
        "achieved": "06-2012",
        "institute": "Universiteit van Amsterdam",
        "city": "Amsterdam",
    },
    "digidproef.address": {
        "street": "Dorpsstraat",
        "houseNumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
    },
    "digidproef.basicPersonalData": {
        "firstnames": "Jan",
        "surname": "de Vries",
        "gender": "M",
        "nationality": "Nederlandse",
        "dateofbirth": "01-01-1990",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
        "bsn": "999999990",
        "photo": "",
    },
    "digidproef.personalData": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "gender": "M",
        "nationality": "Nederlandse",
        "dateofbirth": "01-01-1990",
        "countryofbirth": "Nederland",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
        "bsn": "999999990",
        "photo": "",
        "cityofbirth": "Amsterdam",
    },
    "discipl-pra.demoKeys": {
        "keys": "demo-key-1, demo-key-2",
        "versions": "1.0, 1.1",
    },
    "discipl-pra.demoValue": {
        "key": "demo-key-1",
        "version": "1.0",
        "value": "demo-value",
        "type": "string",
    },
    "discipl.demoBRI": {
        "registeredIncome": "36000",
        "taxYear": "2024",
    },
    "discipl.demoBVV": {
        "calculatedBVV": "1500",
        "debtCollector": "Deurwaarderskantoor Demo",
        "incomeUsedForBVV": "3000",
    },
    "discipl.demoVIL": {
        "woonplaats": "Amsterdam",
        "geboortedatum": "01-01-1990",
        "aowLeeftijdBehaald": "no",
        "ouderDan21": "yes",
        "alleenstaande": "yes",
        "thuiswonendeKinderen": "no",
        "inkomenPerMaand": "3000",
        "vermogen": "5000",
    },
    "enschede.bijstandsgerechtigd": {
        "bijstandsgerechtigd": "yes",
    },
    "forus.demoKindpakket": {
        "kindpakketEligible": "yes",
        "numChildren": "2",
    },
    "geant-incubator.edugain-proxy": {
        "schacHomeOrganization": "example.com",
        "eduPersonScopedAffiliation": "student@example.com",
        "subject-id": "jan.devries@example.com",
        "displayName": "Jan de Vries",
        "givenName": "Jan",
        "sn": "de Vries",
        "mail": "jan.devries@example.com",
        "eduPersonAssurance": "https://refeds.org/assurance/IAP/medium",
    },
    "geant-incubator.surf-sram": {
        "subject-id": "jandevries@demo.example.org",
        "eduPersonPrincipalName": "jandevries@demo.example.org",
        "eduPersonOrcid": "0000-0002-1825-0097",
        "eduperson_unique_id": "jandevries-9f3a8b21",
        "UID": "jdevries",
        "voperson_external_id": "jandevries@demo.example.org",
        "ssh_public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5 jan@demo",
        "schacHomeOrganization": "demo.example.org",
        "displayName": "Jan de Vries",
        "givenName": "Jan",
        "sn": "de Vries",
        "mail": "jan.devries@example.com",
        "eduPersonAffiliation": "staff",
        "eduPersonScopedAffiliation": "staff@demo.example.org",
        "voperson_external_affiliation": "staff@demo.example.org",
        "eduPersonEntitlement": "urn:mace:demo.example.org:demo-access",
        "eduPersonAssurance": "https://refeds.org/assurance/IAP/medium",
    },
    "gebiedonline.locality": {
        "locality": "yes",
        "neighbourhood": "yes",
        "district": "yes",
        "municipality": "Amsterdam",
    },
    "gebiedonline.locality2": {
        "homePostcodeDigits": "1234",
        "workPostcodeDigits": "1011",
    },
    "gebiedonline.stakeholder": {
        "logincode": "GBO-123456",
    },
    "gemeente.address": {
        "street": "Dorpsstraat",
        "houseNumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
    },
    "gemeente.personalData": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "gender": "M",
        "nationality": "Nederlandse",
        "surname": "Vries",
        "dateofbirth": "01-01-1990",
        "cityofbirth": "Amsterdam",
        "countryofbirth": "Nederland",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
        "bsn": "999999990",
        "digidlevel": "Substantieel",
    },
    "gemeenten.address": {
        "street": "Dorpsstraat",
        "houseNumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
    },
    "gemeenten.personalData": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "gender": "M",
        "nationality": "Nederlandse",
        "surname": "Vries",
        "dateofbirth": "01-01-1990",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
        "bsn": "999999990",
        "digidlevel": "Substantieel",
    },
    "ggd.coronatest": {
        "negativetestresult": "yes",
        "kind": "PCR",
        "date": "01-01-2024",
        "performer": "GGD Amsterdam",
        "firstnames": "Jan",
        "familyname": "de Vries",
        "dateofbirth": "01-01-1990",
        "testresult": "negative",
    },
    "haarlem.medewerker": {
        "personeelsnummer": "123456",
        "organisatie": "Gemeente Haarlem",
    },
    "ideal.ideal": {
        "fullname": "Jan de Vries",
        "iban": "NL91ABNA0417164300",
        "bic": "ABNANL2A",
    },
    "idin.ageLimits": {
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
    },
    "idin.idin": {
        "initials": "J.",
        "familyname": "de Vries",
        "dateofbirth": "01-01-1990",
        "gender": "M",
        "address": "Dorpsstraat 1",
        "zipcode": "1234 AB",
        "city": "Amsterdam",
        "country": "Nederland",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
    },
    "interpolis.login": {
        "identifier": "IP-123456789",
    },
    "inz-emailer.email": {
        "email": "jan.devries@example.com",
    },
    "inz-id-card.address": {
        "fullAddress": "Dorpsstraat 1, 1234 AB Amsterdam",
    },
    "inz-id-card.idCard": {
        "firstName": "Jan",
        "lastName": "de Vries",
        "fullName": "Jan de Vries",
        "birthdate": "01-01-1990",
        "over18": "yes",
        "over20": "yes",
        "over65": "no",
        "issueDate": "01-01-2024",
        "expiryDate": "01-01-2030",
        "number": "SPEC12345",
    },
    "inz-internetnz.domain": {
        "name": "example.nl",
    },
    "inz-internetnz.id": {
        "number": "INZ-100245",
    },
    "inz-internetnz.membership": {
        "id": "MEM-100245",
        "type": "Premium",
        "purchaseDate": "01-01-2024",
        "renewalDate": "01-01-2024",
        "validUntil": "01-01-2030",
    },
    "inz-internetnz.nethuiAccessPass": {
        "id": "AP-123456",
        "event": "NetHui 2024",
        "eventDate": "01-01-2024",
        "accessPassType": "Full access",
        "purchaseDate": "01-01-2024",
        "price": "150",
    },
    "inz-internetnz.votingcard": {
        "election": "Gemeenteraadsverkiezingen 2024",
        "start": "01-01-2024",
        "end": "01-01-2030",
        "votingnumber": "1234567890",
    },
    "inz-nhi.nhi": {
        "number": "ABC1234",
    },
    "inz-nsn.nsn": {
        "number": "1234567",
    },
    "inz-personal-data.ageLimits": {
        "over18": "yes",
        "over65": "no",
    },
    "inz-personal-data.birthdate": {
        "birthdate": "01-01-1990",
    },
    "inz-personal-data.personName": {
        "fullName": "Jan de Vries",
    },
    "inz-postal-service.address": {
        "fullAddress": "Dorpsstraat 1, 1234 AB Amsterdam",
    },
    "inz-revocable-id.id": {
        "number": "123456789",
    },
    "irmages.photos": {
        "photo": "",
    },
    "IRMATube.member": {
        "type": "Premium",
        "id": "MEM-100245",
        "fullname": "Jan de Vries",
    },
    "irvn.account": {
        "email": "jan.devries@example.com",
        "domain": "example.com",
        "userid": "jdevries",
        "username": "jan.devries",
    },
    "ivido.login": {
        "identifier": "ivido-jan-de-vries-8f3a",
    },
    "kvk.official": {
        "legalEntity": "Besloten Vennootschap",
        "fullname": "Jan de Vries",
        "position": "Bestuurder",
        "authority": "Alleen/zelfstandig bevoegd",
        "officeAddress": "Dorpsstraat 1, 1234 AB Amsterdam",
        "officePhone": "+31612345678",
        "kvkNumber": "12345678",
        "sbiCode": "6201",
        "referenceMoment": "01-01-2024",
        "rsin": "812345678",
        "name": "Demo B.V.",
        "typeOwner": "Rechtspersoon",
        "emailAddress": "jan.devries@example.com",
        "sbiActivity": "Ontwikkelen van software",
        "registrationStart": "01-01-2024",
        "dateDeregistration": "01-01-2030",
        "registrationEnd": "01-01-2030",
        "specialLegalSituation": "Geen",
        "restrictionInLegalAction": "Geen",
        "foreignLegalStatus": "Geen",
        "lastName": "Vries",
        "prefix": "de",
        "firstNames": "Jan",
        "datOfBirth": "01-01-1990",
        "dateOfDeath": "",
        "typeOfficial": "Bestuurder",
        "jobTitle": "Directeur",
        "kindOfAuthorization": "Volledige volmacht",
        "restrictionInEurosAuthorization": "0",
        "otherRestrictionAuthorization": "no",
        "isAuthorizedWith": "no",
        "typePowerOfAttorney": "Algemeen",
        "restrictioninMoneyPowerOfAttorney": "0",
        "restrictionOnActPowerOfAttorney": "Geen",
        "hasOtherPowerOfAttorney": "no",
        "descriptionOtherPowerOfAttorney": "Geen",
        "permissionToChangeTradeRegister": "yes",
        "specialLegalSituationOfficial": "Geen",
        "restrictionInLegalActionOfficial": "Geen",
        "suspensionStart": "",
        "suspensionEnd": "",
        "emancipationOfMinor": "no",
        "hasRestriction": "no",
        "isAuthorized": "yes",
        "reason": "Bestuurder met volledige bevoegdheid",
        "tradeNames": "Demo B.V.",
    },
    "maas.maasid": {
        "maasid": "MAAS-12345678",
    },
    "MijnOverheid.address": {
        "country": "Nederland",
        "city": "Amsterdam",
        "street": "Dorpsstraat",
        "zipcode": "1234 AB",
    },
    "MijnOverheid.ageHigher": {
        "over50": "no",
        "over60": "no",
        "over65": "no",
        "over75": "no",
    },
    "MijnOverheid.ageLower": {
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
    },
    "MijnOverheid.birthCertificate": {
        "dateofbirth": "01-01-1990",
        "placeofbirth": "Amsterdam",
        "countryofbirth": "Nederland",
        "gender": "M",
    },
    "MijnOverheid.drivinglicense": {
        "firstnames": "Jan",
        "familyname": "de Vries",
        "dateofbirth": "01-01-1990",
        "placeofbirth": "Amsterdam",
        "licensed": "AM, B",
        "country": "Nederland",
        "number": "1234567890",
        "expires": "01-01-2030",
    },
    "MijnOverheid.fullName": {
        "firstnames": "Jan",
        "firstname": "Jan",
        "familyname": "Vries",
        "prefix": "de",
    },
    "MijnOverheid.idDocument": {
        "type": "Paspoort",
        "number": "NL12345678",
        "expires": "01-01-2030",
        "nationality": "Nederlandse",
    },
    "MijnOverheid.root": {
        "BSN": "999999990",
    },
    "nijmegen.address": {
        "street": "Dorpsstraat",
        "houseNumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
    },
    "nijmegen.ageLimits": {
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
    },
    "nijmegen.attestatieDeVita": {
        "naam": "Jan de Vries",
        "geboortedatum": "01-01-1990",
        "verklaring_in_leven": "yes",
        "datum_vaststelling": "01-01-2024",
        "geldig_tot": "01-01-2030",
        "geboorteplaats": "Amsterdam",
        "woonadres": "Dorpsstraat 1",
    },
    "nijmegen.bsn": {
        "bsn": "999999990",
    },
    "nijmegen.deathCertificate": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "dateofbirth": "01-01-1990",
        "dateofdeath": "01-01-2024",
        "gender": "M",
        "surname": "Vries",
        "street": "Dorpsstraat",
        "houseNumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
        "relation": "Partner",
    },
    "nijmegen.employeeData": {
        "email": "jan.devries@example.com",
        "worksForGemeenteNijmegen": "yes",
    },
    "nijmegen.eventPermit": {
        "uniforme_product_naam": "Evenementenvergunning",
        "product_code": "EVT-001",
        "product_naam": "Evenementenvergunning",
        "geldig_van": "01-01-2024",
        "geldig_tot": "01-01-2030",
        "locatie": "Goffertpark, Nijmegen",
        "typeLocatie": "Openbare ruimte",
        "kenmerk": "VERG-2024-0042",
        "bsn": "999999990",
    },
    "nijmegen.huwelijksbevoegdheid": {
        "naam": "Jan de Vries",
        "geboortedatum": "01-01-1990",
        "geboorteplaats": "Amsterdam",
        "nationaliteit": "Nederlandse",
        "burgerlijke_staat": "Ongehuwd",
        "verklaring_geen_huwelijksbeletsel": "yes",
        "datum_afgifte": "01-01-2024",
        "geldig_tot": "01-01-2030",
        "naam_partner": "Maria Jansen",
        "geboortedatum_partner": "05-05-1991",
        "nationaliteit_partner": "Nederlandse",
    },
    "nijmegen.personalData": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "dateofbirth": "01-01-1990",
        "gender": "M",
        "nationality": "Nederlandse",
        "surname": "Vries",
    },
    "nijmegen.streetTradingPermit": {
        "uniforme_product_naam": "Groente en fruit",
        "product_code": "GF-001",
        "product_naam": "Verse groente en fruit",
        "geldig_van": "01-01-2024",
        "geldig_tot": "01-01-2030",
        "locatie": "Grote Markt, Nijmegen",
        "typeLocatie": "Vaste standplaats",
        "kenmerk": "SVP-2024-001",
        "bsn": "999999990",
    },
    "nijmegen.travelDocument": {
        "kind": "Paspoort",
        "number": "NX1234567",
        "issuancedate": "01-01-2024",
        "expirydate": "01-01-2030",
        "documentissuer": "Gemeente Amsterdam",
    },
    "nijmegen.verzorgingsbudget": {
        "budget": "1500",
    },
    "noab.membership": {
        "accountNumber": "NL91ABNA0417164300",
        "personalNumber": "NOAB-300400",
        "authorizedtosign": "yes",
    },
    "nuts.agb": {
        "agbcode": "12345678",
        "role": "Huisarts",
    },
    "pbdf.facebook": {
        "fullname": "Jan de Vries",
        "firstname": "Jan",
        "familyname": "de Vries",
        "email": "jan.devries@example.com",
        "dateofbirth": "01-01-1990",
    },
    "pbdf.linkedin": {
        "fullname": "Jan de Vries",
        "firstname": "Jan",
        "familyname": "de Vries",
        "email": "jan.devries@example.com",
        "profileurl": "https://www.linkedin.com/in/jandevries",
    },
    "pbdf.mobilenumber": {
        "mobilenumber": "+31612345678",
    },
    "pbdf.surfnet-2": {
        "institute": "Universiteit van Amsterdam",
        "type": "Student",
        "id": "10012345",
        "fullid": "uva-10012345",
        "fullname": "Jan de Vries",
        "firstname": "Jan",
        "familyname": "de Vries",
        "email": "jan.devries@example.com",
    },
    "pbdf.twitter": {
        "username": "jandevries",
        "fullname": "Jan de Vries",
        "email": "jan.devries@example.com",
        "profileurl": "https://twitter.com/jandevries",
    },
    "PubHubs.account": {
        "id": "jan-de-vries-7f3a",
        "registration_date": "01-01-2024",
        "registration_source": "Yivi",
    },
    "PubHubs.pubhubsaccount": {
        "email": "jan.devries@example.com",
        "mobilenumber": "+31612345678",
        "registrationdate": "01-01-2024",
    },
    "rdw.vrn": {
        "vrn": "12-ABC-3",
    },
    "RU.idinData": {
        "initials": "J.",
        "familyName": "de Vries",
        "dateOfBirth": "01-01-1990",
        "sex": "M",
        "address": "Dorpsstraat 1",
        "zipcode": "1234 AB",
        "city": "Amsterdam",
    },
    "RU.studentCard": {
        "university": "Radboud Universiteit",
        "studentCardNumber": "1234567890",
        "studentID": "s1234567",
        "level": "regular",
    },
    "sidn-pbdf.email": {
        "email": "jan.devries@example.com",
        "domain": "example.com",
    },
    "sidn-pbdf.mobilenumber": {
        "mobilenumber": "+31612345678",
    },
    "sidn-pbdf.uniqueid": {
        "uniqueid": "JDV-0001",
        "organization": "Demo B.V.",
    },
    "signicat.authorization": {
        "kvkNumber": "12345678",
        "name": "Demo B.V.",
        "authorizationDescription": "Gemachtigd om namens de organisatie te tekenen",
        "lastName": "Vries",
        "prefix": "de",
        "firstNames": "Jan",
        "dateOfBirth": "01-01-1990",
        "rsin": "812345678",
        "tradeNames": "Demo B.V.",
        "legalEntity": "Besloten Vennootschap",
        "address": "Dorpsstraat 1, 1234 AB Amsterdam",
        "sbiActivity": "6201 - Ontwikkelen van software",
        "registrationStart": "01-01-2024",
        "referenceMoment": "01-01-2024",
        "authorizationCode": "AUTH-0001",
        "authorizationDate": "01-01-2024",
        "issuedBy": "Jan de Vries",
        "fullname": "Jan de Vries",
        "euid": "NLKVK.12345678",
    },
    "signicat.kvkTradeRegister": {
        "kvkNumber": "12345678",
        "rsin": "812345678",
        "name": "Demo B.V.",
        "tradeNames": "Demo B.V.",
        "typeOwner": "Rechtspersoon",
        "legalEntity": "Besloten Vennootschap",
        "address": "Dorpsstraat 1",
        "emailAddress": "jan.devries@example.com",
        "phone": "+31612345678",
        "sbiActivity": "6201 - Ontwikkelen van software",
        "registrationStart": "01-01-2024",
        "dateDeregistration": "01-01-2030",
        "registrationEnd": "01-01-2030",
        "specialLegalSituation": "Geen",
        "restrictionInLegalAction": "Geen",
        "foreignLegalStatus": "Geen",
        "lastName": "Vries",
        "prefix": "de",
        "firstNames": "Jan",
        "dateOfBirth": "01-01-1990",
        "dateOfDeath": "Geen",
        "fullname": "Jan de Vries",
        "typeOfficial": "Bestuurder",
        "position": "Directeur",
        "jobTitle": "Directeur",
        "kindOfAuthorization": "Volledig bevoegd",
        "restrictionInEurosAuthorization": "Geen",
        "otherRestrictionAuthorization": "no",
        "isAuthorizedWithOtherPersons": "no",
        "typePowerOfAttorney": "Algehele volmacht",
        "restrictioninMoneyPowerOfAttorney": "Geen",
        "restrictionOnActPowerOfAttorney": "Geen",
        "hasOtherPowerOfAttorney": "no",
        "descriptionOtherPowerOfAttorney": "Geen",
        "permissionToChangeTradeRegister": "yes",
        "specialLegalSituationOfficial": "Geen",
        "restrictionInLegalActionOfficial": "Geen",
        "suspensionStart": "Geen",
        "suspensionEnd": "Geen",
        "emancipationOfMinor": "no",
        "hasRestriction": "no",
        "isAuthorized": "yes",
        "reason": "Bevoegd als bestuurder",
        "referenceMoment": "20240101120000000",
    },
    "staffpass.employeeCard": {
        "cardPassId": "EMP-001234",
        "fullName": "Jan de Vries",
        "orgName": "Demo B.V.",
        "orgLogo": "",
        "role": "Medewerker",
        "jobTitle": "Software Engineer",
        "email": "jan.devries@example.com",
        "kvkNumber": "12345678",
        "photo": "",
    },
    "stemmen.stempas": {
        "election": "Tweede Kamerverkiezingen 2024",
        "votingnumber": "987654321",
        "voteURL": "https://stemmen.example.nl",
        "start": "01-01-2024",
        "end": "01-01-2030",
    },
    "surf.surfdrive": {
        "eppn": "jandevries@demo.example.org",
        "emailadres": "jan.devries@example.com",
        "displayname": "Jan de Vries",
    },
    "suwinet.income": {
        "income": "3000",
    },
    "TNO.first_test": {
        "name": "Jan de Vries",
        "age": "34",
        "dutchCitizen": "yes",
    },
    "tweedegolf.regelregister": {
        "rule": "Stadspas korting",
        "rule_id": "RULE-0042",
        "allowancenumber": "ALW-8f3a21",
        "location": "Gemeente Amsterdam",
        "amount": "50",
    },
    "TWIpilot.TWIattributes": {
        "inleven": "yes",
        "gezinssituatie": "alleenstaand",
        "rechtwtos": "yes",
        "rechtwsf": "yes",
        "ontvangenwajong": "no",
        "medischebeperking": "no",
        "inschrijvingopleiding": "yes",
        "banksaldo": "5000",
        "schulden": "2500",
        "waardepapieren": "1000",
        "bezittingen": "no",
        "aantalkinderen": "2",
        "leeftijdkinderen": "8",
        "reintegratietraject": "no",
        "uwvuitkering": "no",
        "svbuitkering": "no",
        "sociaalmedischeindicatie": "no",
        "overeenkomstkinderopvang": "yes",
        "overzichtkinderopvang": "1200",
        "rechtinkomenstoeslag": "yes",
        "ontvangenioawuitkering": "no",
        "ontvangenbijstandsuitkering": "no",
    },
    "uzipoc-cibg.uzi": {
        "uraName": "Demo Ziekenhuis",
        "uraNumber": "12345678",
        "uziNumber": "900012345",
        "hasRole01-041": "yes",
        "hasRole30-000": "no",
        "hasRole01-010": "no",
        "hasRole01-011": "no",
    },
    "uzipoc-cibg.uzi-2": {
        "initials": "J.",
        "surnamePrefix": "de",
        "surname": "Vries",
        "entityName": "Demo Zorginstelling B.V.",
        "ura": "12345678",
        "uziId": "900123456",
        "roles": "Arts",
        "loaAuthn": "Substantial",
        "loaUzi": "High",
    },
    "uzipoc-cibg.uzi-acceptance": {
        "initials": "J.",
        "surnamePrefix": "de",
        "surname": "Vries",
        "entityName": "Demo Ziekenhuis",
        "ura": "12345678",
        "uziId": "900012345",
        "roles": "Arts",
        "loaAuthn": "Hoog",
        "loaUzi": "Hoog",
    },
    "uzipoc-cibg.uzi-demo": {
        "initials": "J.",
        "surnamePrefix": "de",
        "surname": "Vries",
        "entityName": "Demo B.V.",
        "ura": "12345678",
        "uziId": "900012345",
        "roles": "Huisarts",
        "loaAuthn": "Substantieel",
        "loaUzi": "Hoog",
    },
    "uzipoc-cibg.uzi-proeftuin": {
        "initials": "J.",
        "surnamePrefix": "de",
        "surname": "Vries",
        "entityName": "Demo B.V.",
        "ura": "12345678",
        "uziId": "900012345",
        "roles": "Arts",
        "loaAuthn": "Substantieel",
        "loaUzi": "Hoog",
    },
    "VeriD.actualWage": {
        "wage": "3000",
        "period": "01-01-2024 tot 31-01-2024",
        "kind": "Loon uit dienstbetrekking",
        "range": "2500-3500",
    },
    "VeriD.bankcard": {
        "logo": "",
        "accountNumber": "NL91ABNA0417164300",
        "cardNumber": "6731 1234 5678 9012",
        "cardHolderName": "Jan de Vries",
        "expirationDate": "01-01-2030",
        "issuerInfo": "De Hollandsche Bank",
    },
    "VeriD.bankIncomeProfile": {
        "rekeninghouder": "Jan de Vries",
        "bankrekening": "NL91ABNA0417164300",
        "uitgever": "De Hollandsche Bank",
        "datum_uitgifte": "01-01-2024",
        "inkomensprofiel_gelijk": "yes",
    },
    "VeriD.basicPersonalData": {
        "firstnames": "Jan",
        "surname": "de Vries",
    },
    "VeriD.belastingdienstmiddeling": {
        "box1Income2012": "30000",
        "box1Income2013": "31000",
        "box1Income2014": "32000",
        "box1Income2015": "33000",
        "box1Income2016": "34000",
        "box1Income2017": "35000",
        "box1Income2018": "36000",
        "box1Income2019": "37000",
        "box1Income2020": "38000",
        "box1Income2021": "39000",
        "box1Income2022": "40000",
    },
    "VeriD.currentIncome": {
        "employmentIncome": "3000",
        "benefitIncome": "0",
        "benefits": "0",
        "entrepeneurIncome": "0",
        "taxCredits": "150",
        "rentAllowance": "200",
        "healtcareAllowance": "100",
        "childrelatedBudget": "250",
        "alimony": "500",
        "other": "0",
    },
    "VeriD.debts": {
        "rent": "1200",
        "mortgage": "0",
        "healthcareInsurance": "135",
        "taxes": "250",
        "loan": "150",
        "cityTaxes": "45",
        "phone": "+31612345678",
        "other": "100",
    },
    "VeriD.digitalInsurancePassport": {
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "surname": "Vries",
        "dateofbirth": "01-01-1990",
        "legalInsuranceChecks": "No hits",
    },
    "VeriD.duoStatus": {
        "student": "yes",
        "studentFinance": "yes",
        "travelProduct": "yes",
        "performanceGrant": "yes",
        "studentDebt": "2500",
    },
    "VeriD.ehic": {
        "name": "de Vries",
        "given_names": "Jan",
        "date_of_birth": "01-01-1990",
        "personal_identification_number": "999999990",
        "identification_number_of_the_institution": "7012",
        "identification_number_of_the_card": "80123456789012345678",
        "expiry_date": "01-01-2030",
        "policy_name": "Basisverzekering",
        "monthly_fee": "135",
    },
    "VeriD.eventTicket": {
        "fullname": "Jan de Vries",
        "age": "34",
        "over18": "yes",
        "eventName": "Demo Festival 2024",
        "ticket": "TICKET-2024-00125",
    },
    "VeriD.familyComposition": {
        "partnerName": "Maria de Vries",
        "partnerBirthdate": "05-05-1991",
        "child1Name": "Sophie de Vries",
        "child1Birthdate": "10-03-2015",
        "child2Name": "Lucas de Vries",
        "child2Birthdate": "22-07-2017",
        "child3Name": "Emma de Vries",
        "child3Birthdate": "14-11-2019",
    },
    "VeriD.gezagsbevestiging": {
        "naam_kind": "Sophie de Vries",
        "geboortedatum_kind": "01-01-2015",
        "naam_ouder": "Jan de Vries",
        "gezagsrelatie": "Ouder met gezag",
        "gezag_bevestigd": "yes",
        "bron": "BRP",
        "datum_afgifte": "01-01-2024",
    },
    "VeriD.guardianship": {
        "guardianship": "no",
    },
    "VeriD.imic": {
        "logo": "",
        "customerNumber": "1234567",
        "policyNumber": "POL-1234567",
        "issuedUnderTheAuthorityOf": "De Hollandsche Bank",
        "coverageStartDate": "01-01-2024",
        "coverageEndDate": "01-01-2030",
        "countryCodeInsurer": "NL",
        "vehicleRegistrationNumber": "12-ABC-3",
        "vehicleCategory": "B",
        "vehicleCategoryDescription": "Personenauto",
        "vehicleMake": "Volkswagen",
        "vehicleModel": "Golf",
        "coverageAreas": "EU",
        "policyholderName": "Jan de Vries",
        "policyholderAddress": "Dorpsstraat 1",
        "issuer": "De Hollandsche Bank",
    },
    "VeriD.landlordDeclartion": {
        "tenantInitials": "J.",
        "tenantFirstnames": "Jan",
        "tenantPrefix": "de",
        "tenantFamilyname": "Vries",
        "tenantBirthdate": "01-01-1990",
        "street": "Dorpsstraat",
        "housenumber": "1",
        "zipcode": "1234 AB",
        "city": "Amsterdam",
        "tenancyStartDate": "01-01-2024",
        "tenancyEndDate": "01-01-2030",
        "rentPerMonth": "1200",
        "serviceChargesPerMonth": "150",
        "paymentArrears": "0",
        "tenantConduct": "Geen klachten",
        "landlordName": "Demo B.V.",
        "landlordContact": "jan.devries@example.com",
        "issuancedate": "01-01-2024",
    },
    "VeriD.mandate": {
        "mandator_bsn": "999999990",
        "mandatary_bsn": "999999990",
        "scope": "Belastingaangifte",
        "type": "Voor een specifieke periode",
        "end_date": "01-01-2030",
        "kvk_number": "12345678",
    },
    "VeriD.maritalStatus": {
        "married": "yes",
        "registeredPartnershp": "no",
        "unmarried": "no",
        "divorced": "no",
    },
    "VeriD.monthlyCosts": {
        "rent": "1200",
        "mortgage": "0",
        "utilities": "180",
        "healtcarehInsurance": "140",
        "householdInsurance": "15",
        "liabilityInsurance": "8",
        "telephone": "+31612345678",
        "internet": "45",
        "television": "20",
        "cityTaxes": "30",
        "waterTaxes": "20",
        "carInsurance": "60",
        "motorTax": "45",
        "studyCosts": "0",
        "alimony": "500",
        "childcare": "350",
        "other": "100",
    },
    "VeriD.monthlyRedemption": {
        "rent": "1200",
        "mortgage": "0",
        "utilities": "200",
        "healtcarehInsurance": "140",
        "householdInsurance": "15",
        "liabilityInsurance": "10",
        "telephone": "+31612345678",
        "internet": "45",
        "television": "20",
        "cityTaxes": "50",
        "waterTaxes": "25",
        "carInsurance": "60",
        "motorTax": "40",
        "studyCosts": "0",
        "alimony": "500",
        "childcare": "300",
        "other": "100",
    },
    "VeriD.nibud": {
        "below": "yes",
        "above": "no",
    },
    "VeriD.paymentDelinquency": {
        "paymentDelinquency": "no",
    },
    "VeriD.personalData": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "gender": "M",
        "nationality": "Nederlandse",
        "surname": "Vries",
        "dateofbirth": "01-01-1990",
        "cityofbirth": "Amsterdam",
        "countryofbirth": "Nederland",
        "over12": "yes",
        "over16": "yes",
        "over18": "yes",
        "over21": "yes",
        "over65": "no",
        "bsn": "999999990",
        "digidlevel": "Substantieel",
        "guardian": "Niet van toepassing",
    },
    "VeriD.postnl": {
        "customerID": "CUST123456",
        "deliveryPreference": "address",
        "notAtHomePreference": "neighbours",
        "shippingMethodPreference": "parcel",
        "over18": "yes",
    },
    "VeriD.seizure": {
        "seizure": "no",
    },
    "VeriD.seizures": {
        "seizure": "no",
        "income": "no",
        "welfare": "no",
        "house": "no",
        "bank": "no",
        "amount": "0",
    },
    "VeriD.successionCertificate": {
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "fullname": "Jan de Vries",
        "dateofbirth": "01-01-1990",
        "dateofdeath": "01-01-2024",
        "gender": "M",
        "surname": "Vries",
        "street": "Dorpsstraat",
        "housenumber": "1",
        "zipcode": "1234 AB",
        "municipality": "Amsterdam",
        "city": "Amsterdam",
        "will": "yes",
        "heirs": "Maria de Vries, Sophie de Vries",
        "executor": "Maria de Vries",
        "issuancedate": "01-01-2024",
    },
    "VeriD.tinkAccountCheck": {
        "accountNumber": "NL91ABNA0417164300",
        "IBAN": "NL91ABNA0417164300",
        "holderName": "Jan de Vries",
        "currencyCode": "EUR",
        "parties": "Jan de Vries",
        "name": "Betaalrekening",
    },
    "VeriD.toestemmingReizenMinderjarige": {
        "toestemming_andere_ouder": "yes",
        "naam_andere_ouder": "Marie de Vries",
        "datum_toestemming": "01-01-2024",
        "geldigheid_periode": "01-01-2024 - 01-01-2030",
        "digitale_handtekening_ouders": "J. de Vries, M. de Vries",
    },
    "VeriD.vergoedingenpas": {
        "logo": "",
        "barcode": "9789012345678",
        "region": "Amsterdam",
        "postalcode": "1234 AB",
        "over18": "yes",
        "over65": "no",
        "photo": "",
    },
    "VeriD.waterBoardTax": {
        "pay_for_date": "01-03-2024",
        "document_date": "01-01-2024",
        "subject_number": "123456789",
        "assessment_number": "2024-987654",
        "tax_year": "2024",
        "amount_due": "350",
        "address_street": "Dorpsstraat",
        "address_house_number": "1",
        "address_zipcode": "1234 AB",
        "address_city": "Amsterdam",
        "roads_user_levy": "75",
        "water_system_levy_user": "120",
        "waste_water_treatment_levy_home": "155",
        "water_board": "Waterschap Amstel, Gooi en Vecht",
    },
    "vgz.machtiging": {
        "clientnumber": "VGZ12345678",
        "clientfullname": "Jan de Vries",
        "mandateid": "MND-123456",
    },
    "vngrealisatie.fieldlabparticipant": {
        "edition": "Fieldlab 2024",
        "participantid": "FL-2024-0123",
    },
    "vzvz.healthcareidentity": {
        "healthcarecode": "999999990",
        "initials": "J.",
        "firstnames": "Jan",
        "prefix": "de",
        "familyname": "Vries",
        "dateofbirth": "01-01-1990",
        "issuancemethod": "DigiD",
    },
    "wigo4it.stadspas": {
        "stadspas": "yes",
    },
}
