name: Build Django container

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths-ignore:
      - portal_spa/**
      - .github/workflows/react-*.yml
  push:
    branches: [main]
    paths-ignore:
      - portal_spa/**
      - .github/workflows/react-*.yml
  release:
    # Note: a current limitation is that when a release is edited after publication, then the Docker tags are not automatically updated.
    types: [published]
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  TEST_TAG: privacybydesign/portal-api:test

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check whether this event is the HEAD of main
        continue-on-error: true
        id: is-head-main
        run: git rev-parse HEAD | grep -x ${{ github.sha }}
        shell: bash

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/privacybydesign/django-portal
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=edge,enable=${{ steps.is-head-main.outcome == 'success' }}
            type=ref,event=branch,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.django
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run tests
        run: |
          docker run --env-file .env.testing --rm ${{ env.TEST_TAG }} python manage.py test

      - name: Build container and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.django
          push: ${{ ! contains(fromJSON('["schedule", "pull_request"]'), github.event_name) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
