name: Ruff Linter

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - portal_spa/**
      - .github/workflows/react-*.yml

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install Ruff
        run: |
          pip install ruff

      - name: Run Ruff linter
        run: |
          ruff check .
