name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dockerfile build stage
        run: docker build -t privacybydesign/react-portal:build .
